### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by havi05** [davthedev/Godolights-DMX#1]
I want to motivate you to keep programming on this cool thing!!!

Gamemap

**Comment by davthedev** [comment]
I found other solutions in the meantime, because binding a DMX512 control library into a Godot plugin is complex.
Different ones are available depending on the operating system, most require some complex setup and dependencies that are not compatible with easy distribution of the finished game or tool. The support of different DMX512 input/output interfaces is also challenging.

One successful experiment was to use Chataigne and map the light control sequences there. The communication between the Godot game and Chataigne can be done using sockets.

**Comment by havi05** [comment]
Thank you very much!
I implemented the ArtNet Protocol with GDscript, but I will look into this programm.
Thank you for answering.
